defaults: &defaults
  adapter: postgresql
  encoding: unicode
  database: myapp_test
  pool: 5
  username: opensources_cms
  password: openpassword
  encoding: utf8

development:
  adapter: postgresql
  encoding: unicode
  database: opensources_cms
  pool: 5
  username: opensources_cms
  password: openpassword

test:
  adapter: postgresql
  encoding: unicode
  database: myapp_test
  pool: 5
  username: opensources_cms
  password: openpassword


production:
  <<: *defaults
  encoding: utf8
  min_messages: WARNING
  url: <%= ENV['DATABASE_URL'].inspect if ENV['DATABASE_URL'] %>
  database: <%= 'opensources_app_prod' unless ENV['DATABASE_URL'] %>
